// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/analizadorlexicozamoranoomar/LexerCUP.flex

package analizadorlexicozamoranoomar;
import java_cup.runtime.Symbol; 

@SuppressWarnings("fallthrough")
public class LexerCUP implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\22\0\1\1\1\0"+
    "\1\5\5\0\1\6\1\7\2\0\1\10\1\11\1\12"+
    "\1\13\12\14\1\0\1\15\1\16\1\17\1\16\2\0"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\2\26\1\27"+
    "\3\26\1\30\1\31\1\32\1\26\1\25\1\33\1\34"+
    "\1\35\1\36\1\26\1\37\1\26\1\40\1\26\1\41"+
    "\1\42\1\43\1\0\1\44\1\0\1\45\1\46\1\47"+
    "\1\50\1\51\1\52\1\53\1\54\1\55\1\56\1\26"+
    "\1\57\1\60\1\61\1\62\1\63\1\26\1\64\1\65"+
    "\1\66\1\67\1\70\1\71\1\72\1\73\1\26\1\74"+
    "\1\0\1\75\7\0\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\1\5\1\6"+
    "\1\1\1\7\1\1\1\10\1\11\1\12\1\13\12\14"+
    "\1\15\1\16\21\14\1\17\1\20\1\0\1\21\1\0"+
    "\1\2\1\0\1\12\26\14\1\22\25\14\1\10\2\14"+
    "\1\23\1\24\2\14\1\13\1\14\1\25\1\26\14\14"+
    "\1\27\4\14\1\30\1\31\6\14\1\30\11\14\1\32"+
    "\6\14\1\33\1\34\2\14\1\35\17\14\1\36\1\14"+
    "\1\37\1\14\1\26\7\14\1\40\7\14\1\41\5\14"+
    "\1\30\1\42\1\43\6\14\1\44\15\14\1\34\3\14"+
    "\1\45\2\14";

  private static int [] zzUnpackAction() {
    int [] result = new int[225];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\76\0\174\0\76\0\272\0\76\0\76\0\76"+
    "\0\370\0\76\0\u0136\0\u0174\0\76\0\u01b2\0\u01b2\0\u01f0"+
    "\0\u022e\0\u026c\0\u02aa\0\u02e8\0\u0326\0\u0364\0\u03a2\0\u03e0"+
    "\0\u041e\0\76\0\76\0\u045c\0\u049a\0\u04d8\0\u0516\0\u0554"+
    "\0\u0592\0\u05d0\0\u060e\0\u064c\0\u068a\0\u06c8\0\u0706\0\u0744"+
    "\0\u0782\0\u07c0\0\u07fe\0\u083c\0\76\0\76\0\272\0\76"+
    "\0\u087a\0\u08b8\0\u08f6\0\76\0\u0934\0\u0972\0\u09b0\0\u09ee"+
    "\0\u0a2c\0\u0a6a\0\u0aa8\0\u0ae6\0\u0b24\0\u0b62\0\u0ba0\0\u0bde"+
    "\0\u0c1c\0\u0c5a\0\u0c98\0\u0cd6\0\u0d14\0\u0d52\0\u0d90\0\u0dce"+
    "\0\u0e0c\0\u0e4a\0\u026c\0\u0e88\0\u0ec6\0\u0f04\0\u0f42\0\u0f80"+
    "\0\u0fbe\0\u0ffc\0\u103a\0\u1078\0\u10b6\0\u10f4\0\u1132\0\u1170"+
    "\0\u11ae\0\u11ec\0\u122a\0\u1268\0\u12a6\0\u12e4\0\u1322\0\u1360"+
    "\0\u08f6\0\u139e\0\u13dc\0\u026c\0\u026c\0\u141a\0\u1458\0\u026c"+
    "\0\u1496\0\u026c\0\u026c\0\u14d4\0\u1512\0\u1550\0\u158e\0\u15cc"+
    "\0\u160a\0\u1648\0\u1686\0\u16c4\0\u1702\0\u1740\0\u177e\0\u026c"+
    "\0\u17bc\0\u17fa\0\u1838\0\u1876\0\u026c\0\u026c\0\u18b4\0\u18f2"+
    "\0\u1930\0\u196e\0\u19ac\0\u19ea\0\u1a28\0\u1a66\0\u1aa4\0\u1ae2"+
    "\0\u1b20\0\u1b5e\0\u1b9c\0\u1bda\0\u1c18\0\u1c56\0\u026c\0\u1c94"+
    "\0\u1cd2\0\u1d10\0\u1d4e\0\u1d8c\0\u1dca\0\u026c\0\u1e08\0\u1e46"+
    "\0\u1e84\0\u026c\0\u1ec2\0\u1f00\0\u1f3e\0\u1f7c\0\u1fba\0\u1ff8"+
    "\0\u2036\0\u2074\0\u20b2\0\u20f0\0\u212e\0\u216c\0\u21aa\0\u21e8"+
    "\0\u2226\0\u026c\0\u2264\0\u026c\0\u22a2\0\u22e0\0\u231e\0\u235c"+
    "\0\u239a\0\u23d8\0\u2416\0\u2454\0\u2492\0\u026c\0\u24d0\0\u250e"+
    "\0\u254c\0\u258a\0\u25c8\0\u2606\0\u2644\0\u026c\0\u2682\0\u26c0"+
    "\0\u26fe\0\u273c\0\u277a\0\u2644\0\u026c\0\u026c\0\u27b8\0\u27f6"+
    "\0\u2834\0\u2872\0\u28b0\0\u28ee\0\u026c\0\u292c\0\u296a\0\u29a8"+
    "\0\u29e6\0\u2a24\0\u2a62\0\u2aa0\0\u2ade\0\u2b1c\0\u2b5a\0\u2b98"+
    "\0\u2bd6\0\u2c14\0\u026c\0\u2c52\0\u2c90\0\u2cce\0\u026c\0\u2d0c"+
    "\0\u2d4a";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[225];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\0\1\3\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\22\1\24\1\22\1\25"+
    "\2\22\1\26\1\22\1\27\1\30\1\22\1\31\1\22"+
    "\1\32\1\2\1\33\1\22\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\2\22\1\42\1\22\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\1\51\1\22\1\52\1\53\1\54"+
    "\2\22\1\55\1\56\77\0\1\3\2\0\1\3\71\0"+
    "\5\57\1\60\34\57\1\61\33\57\14\0\1\14\74\0"+
    "\1\62\74\0\1\63\1\0\1\14\100\0\1\64\72\0"+
    "\1\22\3\0\16\22\1\65\2\22\3\0\30\22\16\0"+
    "\1\22\3\0\20\22\1\66\3\0\30\22\16\0\1\22"+
    "\3\0\21\22\3\0\30\22\16\0\1\22\3\0\4\22"+
    "\1\67\12\22\1\31\1\22\3\0\30\22\16\0\1\22"+
    "\3\0\17\22\1\31\1\22\3\0\30\22\16\0\1\22"+
    "\3\0\11\22\1\70\7\22\3\0\15\22\1\71\12\22"+
    "\16\0\1\22\3\0\21\22\3\0\17\22\1\72\10\22"+
    "\16\0\1\22\3\0\4\22\1\73\14\22\3\0\30\22"+
    "\16\0\1\22\3\0\1\22\1\21\17\22\3\0\30\22"+
    "\16\0\1\22\3\0\12\22\1\74\6\22\3\0\30\22"+
    "\16\0\1\22\3\0\21\22\3\0\4\22\1\75\23\22"+
    "\16\0\1\22\3\0\21\22\3\0\11\22\1\76\4\22"+
    "\1\77\10\22\1\100\16\0\1\22\3\0\21\22\3\0"+
    "\10\22\1\101\2\22\1\102\2\22\1\103\11\22\16\0"+
    "\1\22\3\0\21\22\3\0\5\22\1\104\10\22\1\105"+
    "\11\22\16\0\1\22\3\0\21\22\3\0\13\22\1\106"+
    "\1\22\1\107\10\22\1\110\1\22\16\0\1\22\3\0"+
    "\21\22\3\0\13\22\1\111\2\22\1\112\11\22\16\0"+
    "\1\22\3\0\21\22\3\0\6\22\1\113\5\22\1\114"+
    "\1\115\12\22\16\0\1\22\3\0\21\22\3\0\5\22"+
    "\1\76\10\22\1\116\11\22\16\0\1\22\3\0\21\22"+
    "\3\0\1\22\1\117\3\22\1\120\15\22\1\121\4\22"+
    "\16\0\1\22\3\0\21\22\3\0\3\22\1\122\1\22"+
    "\1\123\22\22\16\0\1\22\3\0\21\22\3\0\2\22"+
    "\1\124\14\22\1\72\2\22\1\125\1\22\1\126\3\22"+
    "\16\0\1\22\3\0\21\22\3\0\5\22\1\127\12\22"+
    "\1\130\2\22\1\131\4\22\16\0\1\22\3\0\21\22"+
    "\3\0\5\22\1\132\22\22\16\0\1\22\3\0\21\22"+
    "\3\0\5\22\1\133\14\22\1\134\5\22\16\0\1\22"+
    "\3\0\21\22\3\0\15\22\1\135\12\22\16\0\1\22"+
    "\3\0\21\22\3\0\1\22\1\136\7\22\1\137\16\22"+
    "\16\0\1\22\3\0\21\22\3\0\10\22\1\140\17\22"+
    "\2\0\2\57\3\0\71\57\2\62\3\0\71\62\14\0"+
    "\1\141\75\0\1\22\3\0\15\22\1\142\3\22\3\0"+
    "\30\22\16\0\1\22\3\0\15\22\1\143\3\22\3\0"+
    "\30\22\16\0\1\22\3\0\2\22\1\144\16\22\3\0"+
    "\30\22\16\0\1\22\3\0\2\22\1\145\16\22\3\0"+
    "\30\22\16\0\1\22\3\0\21\22\3\0\17\22\1\146"+
    "\10\22\16\0\1\22\3\0\21\22\3\0\5\22\1\147"+
    "\22\22\16\0\1\22\3\0\15\22\1\150\3\22\3\0"+
    "\30\22\16\0\1\22\3\0\13\22\1\151\5\22\3\0"+
    "\30\22\16\0\1\22\3\0\21\22\3\0\4\22\1\152"+
    "\23\22\16\0\1\22\3\0\21\22\3\0\22\22\1\153"+
    "\5\22\16\0\1\22\3\0\21\22\3\0\16\22\1\154"+
    "\11\22\16\0\1\22\3\0\21\22\3\0\22\22\1\155"+
    "\5\22\16\0\1\22\3\0\21\22\3\0\1\22\1\136"+
    "\26\22\16\0\1\22\3\0\21\22\3\0\1\22\1\156"+
    "\26\22\16\0\1\22\3\0\21\22\3\0\14\22\1\157"+
    "\1\160\12\22\16\0\1\22\3\0\21\22\3\0\3\22"+
    "\1\161\24\22\16\0\1\22\3\0\21\22\3\0\23\22"+
    "\1\162\4\22\16\0\1\22\3\0\21\22\3\0\11\22"+
    "\1\163\7\22\1\164\6\22\16\0\1\22\3\0\21\22"+
    "\3\0\23\22\1\165\4\22\16\0\1\22\3\0\21\22"+
    "\3\0\22\22\1\166\5\22\16\0\1\22\3\0\21\22"+
    "\3\0\16\22\1\167\11\22\16\0\1\22\3\0\21\22"+
    "\3\0\20\22\1\170\7\22\16\0\1\22\3\0\21\22"+
    "\3\0\17\22\1\171\10\22\16\0\1\22\3\0\21\22"+
    "\3\0\17\22\1\146\2\22\1\153\5\22\16\0\1\22"+
    "\3\0\21\22\3\0\15\22\1\172\12\22\16\0\1\22"+
    "\3\0\21\22\3\0\11\22\1\173\16\22\16\0\1\22"+
    "\3\0\21\22\3\0\22\22\1\174\5\22\16\0\1\22"+
    "\3\0\21\22\3\0\22\22\1\175\5\22\16\0\1\22"+
    "\3\0\21\22\3\0\10\22\1\101\17\22\16\0\1\22"+
    "\3\0\21\22\3\0\25\22\1\176\2\22\16\0\1\22"+
    "\3\0\21\22\3\0\12\22\1\177\15\22\16\0\1\22"+
    "\3\0\21\22\3\0\10\22\1\200\17\22\16\0\1\22"+
    "\3\0\21\22\3\0\5\22\1\201\22\22\16\0\1\22"+
    "\3\0\21\22\3\0\20\22\1\202\7\22\16\0\1\22"+
    "\3\0\21\22\3\0\11\22\1\203\4\22\1\204\11\22"+
    "\16\0\1\22\3\0\21\22\3\0\2\22\1\205\25\22"+
    "\16\0\1\22\3\0\21\22\3\0\11\22\1\206\10\22"+
    "\1\207\5\22\16\0\1\22\3\0\21\22\3\0\22\22"+
    "\1\150\5\22\16\0\1\22\3\0\21\22\3\0\1\22"+
    "\1\210\16\22\1\211\7\22\16\0\1\22\3\0\21\22"+
    "\3\0\21\22\1\212\6\22\16\0\1\22\3\0\21\22"+
    "\3\0\20\22\1\153\7\22\16\0\1\22\3\0\21\22"+
    "\3\0\20\22\1\213\7\22\16\0\1\22\3\0\21\22"+
    "\3\0\11\22\1\214\16\22\16\0\1\22\3\0\12\22"+
    "\1\215\6\22\3\0\30\22\16\0\1\22\3\0\4\22"+
    "\1\153\14\22\3\0\30\22\16\0\1\22\3\0\21\22"+
    "\3\0\23\22\1\216\4\22\16\0\1\22\3\0\21\22"+
    "\3\0\15\22\1\217\12\22\16\0\1\22\3\0\3\22"+
    "\1\153\15\22\3\0\30\22\16\0\1\22\3\0\21\22"+
    "\3\0\13\22\1\220\14\22\16\0\1\22\3\0\21\22"+
    "\3\0\5\22\1\153\22\22\16\0\1\22\3\0\21\22"+
    "\3\0\21\22\1\221\6\22\16\0\1\22\3\0\21\22"+
    "\3\0\17\22\1\222\10\22\16\0\1\22\3\0\21\22"+
    "\3\0\21\22\1\223\6\22\16\0\1\22\3\0\21\22"+
    "\3\0\11\22\1\224\16\22\16\0\1\22\3\0\21\22"+
    "\3\0\2\22\1\225\25\22\16\0\1\22\3\0\21\22"+
    "\3\0\6\22\1\226\21\22\16\0\1\22\3\0\21\22"+
    "\3\0\5\22\1\227\22\22\16\0\1\22\3\0\21\22"+
    "\3\0\14\22\1\153\13\22\16\0\1\22\3\0\21\22"+
    "\3\0\5\22\1\230\22\22\16\0\1\22\3\0\21\22"+
    "\3\0\1\22\1\76\26\22\16\0\1\22\3\0\21\22"+
    "\3\0\16\22\1\231\11\22\16\0\1\22\3\0\21\22"+
    "\3\0\7\22\1\153\20\22\16\0\1\22\3\0\21\22"+
    "\3\0\15\22\1\232\12\22\16\0\1\22\3\0\21\22"+
    "\3\0\10\22\1\233\17\22\16\0\1\22\3\0\21\22"+
    "\3\0\5\22\1\234\22\22\16\0\1\22\3\0\21\22"+
    "\3\0\5\22\1\235\22\22\16\0\1\22\3\0\21\22"+
    "\3\0\20\22\1\236\7\22\16\0\1\22\3\0\21\22"+
    "\3\0\21\22\1\237\6\22\16\0\1\22\3\0\21\22"+
    "\3\0\15\22\1\240\6\22\1\241\3\22\16\0\1\22"+
    "\3\0\21\22\3\0\22\22\1\242\5\22\16\0\1\22"+
    "\3\0\21\22\3\0\13\22\1\243\14\22\16\0\1\22"+
    "\3\0\21\22\3\0\6\22\1\244\21\22\16\0\1\22"+
    "\3\0\21\22\3\0\23\22\1\245\4\22\16\0\1\22"+
    "\3\0\21\22\3\0\22\22\1\243\5\22\16\0\1\22"+
    "\3\0\21\22\3\0\11\22\1\116\16\22\16\0\1\22"+
    "\3\0\21\22\3\0\11\22\1\246\16\22\16\0\1\22"+
    "\3\0\21\22\3\0\22\22\1\247\5\22\16\0\1\22"+
    "\3\0\21\22\3\0\13\22\1\250\14\22\16\0\1\22"+
    "\3\0\21\22\3\0\1\251\27\22\16\0\1\22\3\0"+
    "\21\22\3\0\22\22\1\252\5\22\16\0\1\22\3\0"+
    "\21\22\3\0\5\22\1\253\22\22\16\0\1\22\3\0"+
    "\21\22\3\0\21\22\1\254\6\22\16\0\1\22\3\0"+
    "\21\22\3\0\13\22\1\255\14\22\16\0\1\22\3\0"+
    "\21\22\3\0\22\22\1\256\5\22\16\0\1\22\3\0"+
    "\21\22\3\0\14\22\1\257\13\22\16\0\1\22\3\0"+
    "\21\22\3\0\13\22\1\155\14\22\16\0\1\22\3\0"+
    "\21\22\3\0\11\22\1\163\16\22\16\0\1\22\3\0"+
    "\21\22\3\0\20\22\1\260\7\22\16\0\1\22\3\0"+
    "\21\22\3\0\20\22\1\261\7\22\16\0\1\22\3\0"+
    "\21\22\3\0\16\22\1\262\11\22\16\0\1\22\3\0"+
    "\21\22\3\0\3\22\1\76\24\22\16\0\1\22\3\0"+
    "\21\22\3\0\20\22\1\263\7\22\16\0\1\22\3\0"+
    "\21\22\3\0\20\22\1\264\7\22\16\0\1\22\3\0"+
    "\21\22\3\0\11\22\1\265\16\22\16\0\1\22\3\0"+
    "\21\22\3\0\22\22\1\266\5\22\16\0\1\22\3\0"+
    "\21\22\3\0\1\22\1\267\26\22\16\0\1\22\3\0"+
    "\21\22\3\0\5\22\1\270\22\22\16\0\1\22\3\0"+
    "\21\22\3\0\11\22\1\271\16\22\16\0\1\22\3\0"+
    "\21\22\3\0\11\22\1\272\16\22\16\0\1\22\3\0"+
    "\21\22\3\0\20\22\1\273\7\22\16\0\1\22\3\0"+
    "\21\22\3\0\7\22\1\274\20\22\16\0\1\22\3\0"+
    "\21\22\3\0\23\22\1\275\4\22\16\0\1\22\3\0"+
    "\21\22\3\0\5\22\1\276\22\22\16\0\1\22\3\0"+
    "\7\22\1\277\11\22\3\0\30\22\16\0\1\22\3\0"+
    "\21\22\3\0\1\22\1\300\26\22\16\0\1\22\3\0"+
    "\21\22\3\0\5\22\1\301\22\22\16\0\1\22\3\0"+
    "\21\22\3\0\20\22\1\302\7\22\16\0\1\22\3\0"+
    "\21\22\3\0\1\22\1\303\26\22\16\0\1\22\3\0"+
    "\21\22\3\0\15\22\1\304\12\22\16\0\1\22\3\0"+
    "\21\22\3\0\22\22\1\305\5\22\16\0\1\22\3\0"+
    "\21\22\3\0\4\22\1\306\23\22\16\0\1\22\3\0"+
    "\21\22\3\0\25\22\1\307\2\22\16\0\1\22\3\0"+
    "\21\22\3\0\11\22\1\310\16\22\16\0\1\22\3\0"+
    "\21\22\3\0\21\22\1\311\6\22\16\0\1\22\3\0"+
    "\21\22\3\0\22\22\1\312\5\22\16\0\1\22\3\0"+
    "\21\22\3\0\3\22\1\313\24\22\16\0\1\22\3\0"+
    "\21\22\3\0\3\22\1\175\24\22\16\0\1\22\3\0"+
    "\21\22\3\0\5\22\1\314\22\22\16\0\1\22\3\0"+
    "\21\22\3\0\15\22\1\315\12\22\16\0\1\22\3\0"+
    "\21\22\3\0\15\22\1\316\12\22\16\0\1\22\3\0"+
    "\21\22\3\0\1\22\1\317\26\22\16\0\1\22\3\0"+
    "\11\22\1\320\7\22\3\0\30\22\16\0\1\22\3\0"+
    "\21\22\3\0\15\22\1\153\12\22\16\0\1\22\3\0"+
    "\21\22\3\0\26\22\1\153\1\22\16\0\1\22\3\0"+
    "\21\22\3\0\23\22\1\321\4\22\16\0\1\22\3\0"+
    "\21\22\3\0\13\22\1\153\14\22\16\0\1\22\3\0"+
    "\21\22\3\0\11\22\1\322\16\22\16\0\1\22\3\0"+
    "\21\22\3\0\4\22\1\312\23\22\16\0\1\22\3\0"+
    "\21\22\3\0\22\22\1\323\5\22\16\0\1\22\3\0"+
    "\21\22\3\0\5\22\1\175\22\22\16\0\1\22\3\0"+
    "\21\22\3\0\22\22\1\272\5\22\16\0\1\22\3\0"+
    "\21\22\3\0\4\22\1\175\23\22\16\0\1\22\3\0"+
    "\21\22\3\0\5\22\1\324\22\22\16\0\1\22\3\0"+
    "\21\22\3\0\13\22\1\175\14\22\16\0\1\22\3\0"+
    "\2\22\1\325\16\22\3\0\30\22\16\0\1\22\3\0"+
    "\21\22\3\0\3\22\1\326\24\22\16\0\1\22\3\0"+
    "\21\22\3\0\21\22\1\327\6\22\16\0\1\22\3\0"+
    "\21\22\3\0\5\22\1\330\22\22\16\0\1\22\3\0"+
    "\21\22\3\0\4\22\1\153\23\22\16\0\1\22\3\0"+
    "\13\22\1\331\5\22\3\0\30\22\16\0\1\22\3\0"+
    "\21\22\3\0\22\22\1\332\5\22\16\0\1\22\3\0"+
    "\21\22\3\0\5\22\1\333\22\22\16\0\1\22\3\0"+
    "\21\22\3\0\15\22\1\76\12\22\16\0\1\22\3\0"+
    "\4\22\1\334\14\22\3\0\30\22\16\0\1\22\3\0"+
    "\21\22\3\0\16\22\1\335\11\22\16\0\1\22\3\0"+
    "\10\22\1\336\10\22\3\0\30\22\16\0\1\22\3\0"+
    "\21\22\3\0\20\22\1\337\7\22\16\0\1\22\3\0"+
    "\4\22\1\340\14\22\3\0\30\22\16\0\1\22\3\0"+
    "\11\22\1\341\7\22\3\0\30\22\16\0\1\22\3\0"+
    "\15\22\1\145\3\22\3\0\30\22\2\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[11656];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\1\1\3\11\1\1\1\11"+
    "\2\1\1\11\14\1\2\11\21\1\2\11\1\0\1\11"+
    "\1\0\1\1\1\0\1\11\255\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[225];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexerCUP(java.io.Reader in) {
      yyline = 1; 
    yychar = 1; 
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.out.println("Este es un error lexico: "+yytext()+
    ", en la linea: "+yyline+", en la columna: "+yychar);
            }
          // fall through
          case 38: break;
          case 2:
            { /*Ignore*/
            }
          // fall through
          case 39: break;
          case 3:
            { yychar=1;
            }
          // fall through
          case 40: break;
          case 4:
            { return new Symbol(sym.Parentesis_Izq, (int)yychar, yyline, yytext());
            }
          // fall through
          case 41: break;
          case 5:
            { return new Symbol(sym.Parentesis_Der, (int)yychar, yyline, yytext());
            }
          // fall through
          case 42: break;
          case 6:
            { return new Symbol(sym.Coma, (int)yychar, yyline, yytext());
            }
          // fall through
          case 43: break;
          case 7:
            { return new Symbol(sym.Punto, (int)yychar, yyline, yytext());
            }
          // fall through
          case 44: break;
          case 8:
            { return new Symbol(sym.Numero, (int)yychar, yyline, yytext());
            }
          // fall through
          case 45: break;
          case 9:
            { return new Symbol(sym.PuntoComa, (int)yychar, yyline, yytext());
            }
          // fall through
          case 46: break;
          case 10:
            { return new Symbol(sym.Operador_comparativo, (int)yychar, yyline, yytext());
            }
          // fall through
          case 47: break;
          case 11:
            { return new Symbol(sym.Asigna, (int)yychar, yyline, yytext());
            }
          // fall through
          case 48: break;
          case 12:
            { return new Symbol(sym.Identificador, (int)yychar, yyline, yytext());
            }
          // fall through
          case 49: break;
          case 13:
            { return new Symbol(sym.Corchete_Izq, (int)yychar, yyline, yytext());
            }
          // fall through
          case 50: break;
          case 14:
            { return new Symbol(sym.Corchete_Der, (int)yychar, yyline, yytext());
            }
          // fall through
          case 51: break;
          case 15:
            { return new Symbol(sym.Llave_Izq, (int)yychar, yyline, yytext());
            }
          // fall through
          case 52: break;
          case 16:
            { return new Symbol(sym.Llave_Der, (int)yychar, yyline, yytext());
            }
          // fall through
          case 53: break;
          case 17:
            { return new Symbol(sym.Literal, yyline, yycolumn, yytext().substring(1, yytext().length()-1));
            }
          // fall through
          case 54: break;
          case 18:
            { return new Symbol(sym.Si, (int)yychar, yyline, yytext());
            }
          // fall through
          case 55: break;
          case 19:
            { return new Symbol(sym.Decremento, (int)yychar, yyline, yytext());
            }
          // fall through
          case 56: break;
          case 20:
            { return new Symbol(sym.Incremento, (int)yychar, yyline, yytext());
            }
          // fall through
          case 57: break;
          case 21:
            { return new Symbol(sym.Agregador, (int)yychar, yyline, yytext());
            }
          // fall through
          case 58: break;
          case 22:
            { return new Symbol(sym.Tipo_de_dato, (int)yychar, yyline, yytext());
            }
          // fall through
          case 59: break;
          case 23:
            { return new Symbol(sym.Ciclo_Para, (int)yychar, yyline, yytext());
            }
          // fall through
          case 60: break;
          case 24:
            { return new Symbol(sym.Modificador_de_acceso, (int)yychar, yyline, yytext());
            }
          // fall through
          case 61: break;
          case 25:
            { return new Symbol(sym.Generador_de_objetos, (int)yychar, yyline, yytext());
            }
          // fall through
          case 62: break;
          case 26:
            { return new Symbol(sym.Abridor_de_archivos, (int)yychar, yyline, yytext());
            }
          // fall through
          case 63: break;
          case 27:
            { return new Symbol(sym.Sino_pregunta, (int)yychar, yyline, yytext());
            }
          // fall through
          case 64: break;
          case 28:
            { return new Symbol(sym.Sino, (int)yychar, yyline, yytext());
            }
          // fall through
          case 65: break;
          case 29:
            { return new Symbol(sym.Principal, (int)yychar, yyline, yytext());
            }
          // fall through
          case 66: break;
          case 30:
            { return new Symbol(sym.Ingresa, (int)yychar, yyline, yytext());
            }
          // fall through
          case 67: break;
          case 31:
            { return new Symbol(sym.Crear_clase, (int)yychar, yyline, yytext());
            }
          // fall through
          case 68: break;
          case 32:
            { return new Symbol(sym.Imprime, (int)yychar, yyline, yytext());
            }
          // fall through
          case 69: break;
          case 33:
            { return new Symbol(sym.Ciclo_Mientras, (int)yychar, yyline, yytext());
            }
          // fall through
          case 70: break;
          case 34:
            { return new Symbol(sym.Importar, (int)yychar, yyline, yytext());
            }
          // fall through
          case 71: break;
          case 35:
            { return new Symbol(sym.Declarador_de_metodos, (int)yychar, yyline, yytext());
            }
          // fall through
          case 72: break;
          case 36:
            { return new Symbol(sym.Devuelve_valor, (int)yychar, yyline, yytext());
            }
          // fall through
          case 73: break;
          case 37:
            { return new Symbol(sym.Constructor, (int) yychar, yyline, yytext());
            }
          // fall through
          case 74: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
