// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/analizadorlexicozamoranoomar/LexerCUP.flex

package analizadorlexicozamoranoomar;
import java_cup.runtime.Symbol; 

@SuppressWarnings("fallthrough")
public class LexerCUP implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\22\0\1\1\1\0"+
    "\1\5\5\0\1\6\1\7\2\0\1\10\1\11\1\12"+
    "\1\13\12\14\1\0\1\15\1\16\1\17\1\16\2\0"+
    "\1\20\1\21\1\20\1\22\1\23\1\24\10\20\1\25"+
    "\1\20\1\24\1\26\1\27\1\30\2\20\1\31\1\20"+
    "\1\32\1\20\1\33\1\34\1\35\1\0\1\20\1\0"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\1\20\1\50\1\51\1\52\1\53\1\54"+
    "\1\20\1\55\1\56\1\57\1\60\1\61\1\62\1\63"+
    "\1\64\1\20\1\65\1\0\1\66\7\0\1\3\u01a2\0"+
    "\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\1\5\1\6"+
    "\2\1\1\7\1\10\1\11\1\12\6\13\1\14\1\15"+
    "\20\13\1\16\1\17\1\0\1\20\1\0\1\2\1\0"+
    "\1\11\12\13\1\21\26\13\1\7\1\13\1\12\1\13"+
    "\1\22\12\13\1\21\4\13\1\23\6\13\1\23\15\13"+
    "\1\24\20\13\1\25\6\13\1\26\12\13\1\23\1\27"+
    "\5\13\1\30\4\13";

  private static int [] zzUnpackAction() {
    int [] result = new int[167];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\67\0\156\0\67\0\245\0\67\0\67\0\67"+
    "\0\334\0\u0113\0\u014a\0\67\0\u0181\0\u0181\0\u01b8\0\u01ef"+
    "\0\u0226\0\u025d\0\u0294\0\u02cb\0\67\0\67\0\u0302\0\u0339"+
    "\0\u0370\0\u03a7\0\u03de\0\u0415\0\u044c\0\u0483\0\u04ba\0\u04f1"+
    "\0\u0528\0\u055f\0\u0596\0\u05cd\0\u0604\0\u063b\0\67\0\67"+
    "\0\245\0\67\0\u0672\0\u06a9\0\u06e0\0\67\0\u0717\0\u074e"+
    "\0\u0785\0\u07bc\0\u07f3\0\u082a\0\u0861\0\u0898\0\u08cf\0\u0906"+
    "\0\u093d\0\u0974\0\u09ab\0\u09e2\0\u0a19\0\u0a50\0\u0a87\0\u0abe"+
    "\0\u0af5\0\u0b2c\0\u0b63\0\u0b9a\0\u0bd1\0\u0c08\0\u0c3f\0\u0c76"+
    "\0\u0cad\0\u0ce4\0\u0d1b\0\u0d52\0\u0d89\0\u0dc0\0\u0df7\0\u06e0"+
    "\0\u0e2e\0\u01b8\0\u0e65\0\u01b8\0\u0e9c\0\u0ed3\0\u0f0a\0\u0f41"+
    "\0\u0f78\0\u0faf\0\u0fe6\0\u101d\0\u1054\0\u108b\0\u01b8\0\u10c2"+
    "\0\u10f9\0\u1130\0\u1167\0\u01b8\0\u119e\0\u11d5\0\u120c\0\u1243"+
    "\0\u127a\0\u12b1\0\u12e8\0\u131f\0\u1356\0\u138d\0\u13c4\0\u13fb"+
    "\0\u1432\0\u1469\0\u14a0\0\u14d7\0\u150e\0\u1545\0\u157c\0\u15b3"+
    "\0\u01b8\0\u15ea\0\u1621\0\u1658\0\u168f\0\u16c6\0\u16fd\0\u1734"+
    "\0\u176b\0\u17a2\0\u17d9\0\u1810\0\u1847\0\u187e\0\u18b5\0\u18ec"+
    "\0\u1923\0\u01b8\0\u195a\0\u1991\0\u19c8\0\u19ff\0\u1a36\0\u1a6d"+
    "\0\u01b8\0\u1aa4\0\u1adb\0\u1b12\0\u1b49\0\u1b80\0\u1bb7\0\u1bee"+
    "\0\u1c25\0\u1c5c\0\u1c93\0\u1bee\0\u01b8\0\u1cca\0\u1d01\0\u1d38"+
    "\0\u1d6f\0\u1da6\0\u01b8\0\u1ddd\0\u1e14\0\u1e4b\0\u1e82";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[167];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\0\1\3\1\5\1\6\1\7"+
    "\1\10\1\11\1\2\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\17\1\21\2\17\1\22\1\23"+
    "\1\24\1\17\1\25\1\2\1\26\1\17\1\27\1\30"+
    "\1\31\1\32\1\33\2\17\1\34\1\17\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\17\1\44\1\45"+
    "\1\46\2\17\1\47\1\50\70\0\1\3\2\0\1\3"+
    "\62\0\5\51\1\52\26\51\1\53\32\51\14\0\1\13"+
    "\65\0\1\54\65\0\1\55\1\0\1\13\71\0\1\56"+
    "\63\0\1\17\3\0\13\17\3\0\27\17\16\0\1\17"+
    "\3\0\12\17\1\57\3\0\27\17\16\0\1\17\3\0"+
    "\11\17\1\24\1\17\3\0\27\17\16\0\1\17\3\0"+
    "\3\17\1\60\7\17\3\0\27\17\16\0\1\17\3\0"+
    "\1\17\1\20\11\17\3\0\27\17\16\0\1\17\3\0"+
    "\5\17\1\61\5\17\3\0\27\17\16\0\1\17\3\0"+
    "\13\17\3\0\10\17\1\62\4\17\1\63\10\17\1\64"+
    "\16\0\1\17\3\0\13\17\3\0\7\17\1\65\2\17"+
    "\1\66\2\17\1\67\11\17\16\0\1\17\3\0\13\17"+
    "\3\0\4\17\1\70\10\17\1\71\11\17\16\0\1\17"+
    "\3\0\13\17\3\0\14\17\1\72\10\17\1\73\1\17"+
    "\16\0\1\17\3\0\13\17\3\0\12\17\1\74\2\17"+
    "\1\75\11\17\16\0\1\17\3\0\13\17\3\0\14\17"+
    "\1\62\12\17\16\0\1\17\3\0\13\17\3\0\4\17"+
    "\1\62\10\17\1\76\11\17\16\0\1\17\3\0\13\17"+
    "\3\0\1\77\3\17\1\100\15\17\1\101\4\17\16\0"+
    "\1\17\3\0\13\17\3\0\2\17\1\102\24\17\16\0"+
    "\1\17\3\0\13\17\3\0\1\17\1\103\21\17\1\104"+
    "\3\17\16\0\1\17\3\0\13\17\3\0\1\105\3\17"+
    "\1\106\12\17\1\107\2\17\1\110\4\17\16\0\1\17"+
    "\3\0\13\17\3\0\4\17\1\111\22\17\16\0\1\17"+
    "\3\0\13\17\3\0\4\17\1\112\14\17\1\113\5\17"+
    "\16\0\1\17\3\0\13\17\3\0\14\17\1\114\12\17"+
    "\16\0\1\17\3\0\13\17\3\0\1\115\7\17\1\116"+
    "\16\17\16\0\1\17\3\0\13\17\3\0\7\17\1\117"+
    "\17\17\2\0\2\51\3\0\62\51\2\54\3\0\62\54"+
    "\14\0\1\120\66\0\1\17\3\0\10\17\1\121\2\17"+
    "\3\0\27\17\16\0\1\17\3\0\10\17\1\122\2\17"+
    "\3\0\27\17\16\0\1\17\3\0\6\17\1\123\4\17"+
    "\3\0\27\17\16\0\1\17\3\0\13\17\3\0\21\17"+
    "\1\124\5\17\16\0\1\17\3\0\13\17\3\0\15\17"+
    "\1\125\11\17\16\0\1\17\3\0\13\17\3\0\21\17"+
    "\1\126\5\17\16\0\1\17\3\0\13\17\3\0\1\115"+
    "\26\17\16\0\1\17\3\0\13\17\3\0\1\127\26\17"+
    "\16\0\1\17\3\0\13\17\3\0\13\17\1\130\1\131"+
    "\12\17\16\0\1\17\3\0\13\17\3\0\2\17\1\132"+
    "\24\17\16\0\1\17\3\0\13\17\3\0\22\17\1\133"+
    "\4\17\16\0\1\17\3\0\13\17\3\0\22\17\1\134"+
    "\4\17\16\0\1\17\3\0\13\17\3\0\21\17\1\135"+
    "\5\17\16\0\1\17\3\0\13\17\3\0\15\17\1\136"+
    "\11\17\16\0\1\17\3\0\13\17\3\0\17\17\1\137"+
    "\7\17\16\0\1\17\3\0\13\17\3\0\14\17\1\140"+
    "\1\141\11\17\16\0\1\17\3\0\13\17\3\0\10\17"+
    "\1\142\16\17\16\0\1\17\3\0\13\17\3\0\21\17"+
    "\1\143\5\17\16\0\1\17\3\0\13\17\3\0\21\17"+
    "\1\144\5\17\16\0\1\17\3\0\13\17\3\0\7\17"+
    "\1\65\17\17\16\0\1\17\3\0\13\17\3\0\11\17"+
    "\1\145\15\17\16\0\1\17\3\0\13\17\3\0\4\17"+
    "\1\146\22\17\16\0\1\17\3\0\13\17\3\0\17\17"+
    "\1\147\7\17\16\0\1\17\3\0\13\17\3\0\17\17"+
    "\1\150\7\17\16\0\1\17\3\0\13\17\3\0\10\17"+
    "\1\151\4\17\1\152\11\17\16\0\1\17\3\0\13\17"+
    "\3\0\1\17\1\153\25\17\16\0\1\17\3\0\13\17"+
    "\3\0\10\17\1\154\10\17\1\155\5\17\16\0\1\17"+
    "\3\0\13\17\3\0\21\17\1\122\5\17\16\0\1\17"+
    "\3\0\13\17\3\0\1\156\16\17\1\157\7\17\16\0"+
    "\1\17\3\0\13\17\3\0\20\17\1\160\6\17\16\0"+
    "\1\17\3\0\13\17\3\0\17\17\1\124\7\17\16\0"+
    "\1\17\3\0\13\17\3\0\17\17\1\161\7\17\16\0"+
    "\1\17\3\0\13\17\3\0\10\17\1\162\16\17\16\0"+
    "\1\17\3\0\3\17\1\124\7\17\3\0\27\17\16\0"+
    "\1\17\3\0\2\17\1\124\10\17\3\0\27\17\16\0"+
    "\1\17\3\0\13\17\3\0\12\17\1\163\14\17\16\0"+
    "\1\17\3\0\13\17\3\0\4\17\1\124\22\17\16\0"+
    "\1\17\3\0\13\17\3\0\20\17\1\164\6\17\16\0"+
    "\1\17\3\0\13\17\3\0\16\17\1\165\10\17\16\0"+
    "\1\17\3\0\13\17\3\0\20\17\1\62\6\17\16\0"+
    "\1\17\3\0\13\17\3\0\10\17\1\166\16\17\16\0"+
    "\1\17\3\0\13\17\3\0\1\17\1\167\25\17\16\0"+
    "\1\17\3\0\13\17\3\0\13\17\1\124\13\17\16\0"+
    "\1\17\3\0\13\17\3\0\4\17\1\170\22\17\16\0"+
    "\1\17\3\0\13\17\3\0\1\62\26\17\16\0\1\17"+
    "\3\0\13\17\3\0\6\17\1\124\20\17\16\0\1\17"+
    "\3\0\13\17\3\0\16\17\1\137\10\17\16\0\1\17"+
    "\3\0\13\17\3\0\14\17\1\171\12\17\16\0\1\17"+
    "\3\0\13\17\3\0\7\17\1\172\17\17\16\0\1\17"+
    "\3\0\13\17\3\0\4\17\1\173\22\17\16\0\1\17"+
    "\3\0\13\17\3\0\17\17\1\174\7\17\16\0\1\17"+
    "\3\0\13\17\3\0\5\17\1\175\21\17\16\0\1\17"+
    "\3\0\13\17\3\0\20\17\1\176\6\17\16\0\1\17"+
    "\3\0\13\17\3\0\14\17\1\177\6\17\1\200\3\17"+
    "\16\0\1\17\3\0\13\17\3\0\21\17\1\201\5\17"+
    "\16\0\1\17\3\0\13\17\3\0\12\17\1\202\14\17"+
    "\16\0\1\17\3\0\13\17\3\0\5\17\1\203\21\17"+
    "\16\0\1\17\3\0\13\17\3\0\22\17\1\204\4\17"+
    "\16\0\1\17\3\0\13\17\3\0\21\17\1\202\5\17"+
    "\16\0\1\17\3\0\13\17\3\0\10\17\1\205\16\17"+
    "\16\0\1\17\3\0\13\17\3\0\10\17\1\206\16\17"+
    "\16\0\1\17\3\0\13\17\3\0\21\17\1\207\5\17"+
    "\16\0\1\17\3\0\13\17\3\0\12\17\1\210\14\17"+
    "\16\0\1\17\3\0\13\17\3\0\4\17\1\211\22\17"+
    "\16\0\1\17\3\0\13\17\3\0\20\17\1\212\6\17"+
    "\16\0\1\17\3\0\13\17\3\0\12\17\1\213\14\17"+
    "\16\0\1\17\3\0\13\17\3\0\13\17\1\214\13\17"+
    "\16\0\1\17\3\0\13\17\3\0\12\17\1\126\14\17"+
    "\16\0\1\17\3\0\13\17\3\0\17\17\1\215\7\17"+
    "\16\0\1\17\3\0\13\17\3\0\15\17\1\216\11\17"+
    "\16\0\1\17\3\0\13\17\3\0\2\17\1\62\24\17"+
    "\16\0\1\17\3\0\13\17\3\0\17\17\1\217\7\17"+
    "\16\0\1\17\3\0\13\17\3\0\15\17\1\75\11\17"+
    "\16\0\1\17\3\0\13\17\3\0\10\17\1\220\16\17"+
    "\16\0\1\17\3\0\13\17\3\0\21\17\1\221\5\17"+
    "\16\0\1\17\3\0\13\17\3\0\1\222\26\17\16\0"+
    "\1\17\3\0\13\17\3\0\4\17\1\223\22\17\16\0"+
    "\1\17\3\0\13\17\3\0\10\17\1\224\16\17\16\0"+
    "\1\17\3\0\13\17\3\0\10\17\1\225\16\17\16\0"+
    "\1\17\3\0\13\17\3\0\17\17\1\226\7\17\16\0"+
    "\1\17\3\0\13\17\3\0\14\17\1\140\12\17\16\0"+
    "\1\17\3\0\13\17\3\0\6\17\1\227\20\17\16\0"+
    "\1\17\3\0\13\17\3\0\22\17\1\230\4\17\16\0"+
    "\1\17\3\0\13\17\3\0\4\17\1\137\22\17\16\0"+
    "\1\17\3\0\13\17\3\0\1\231\26\17\16\0\1\17"+
    "\3\0\13\17\3\0\4\17\1\232\22\17\16\0\1\17"+
    "\3\0\13\17\3\0\1\233\26\17\16\0\1\17\3\0"+
    "\13\17\3\0\14\17\1\234\12\17\16\0\1\17\3\0"+
    "\13\17\3\0\3\17\1\235\23\17\16\0\1\17\3\0"+
    "\13\17\3\0\10\17\1\236\16\17\16\0\1\17\3\0"+
    "\13\17\3\0\20\17\1\237\6\17\16\0\1\17\3\0"+
    "\13\17\3\0\21\17\1\240\5\17\16\0\1\17\3\0"+
    "\13\17\3\0\2\17\1\241\24\17\16\0\1\17\3\0"+
    "\13\17\3\0\2\17\1\144\24\17\16\0\1\17\3\0"+
    "\13\17\3\0\4\17\1\242\22\17\16\0\1\17\3\0"+
    "\13\17\3\0\14\17\1\243\12\17\16\0\1\17\3\0"+
    "\13\17\3\0\14\17\1\244\12\17\16\0\1\17\3\0"+
    "\13\17\3\0\1\245\26\17\16\0\1\17\3\0\13\17"+
    "\3\0\14\17\1\124\12\17\16\0\1\17\3\0\13\17"+
    "\3\0\25\17\1\124\1\17\16\0\1\17\3\0\13\17"+
    "\3\0\12\17\1\124\14\17\16\0\1\17\3\0\13\17"+
    "\3\0\3\17\1\240\23\17\16\0\1\17\3\0\13\17"+
    "\3\0\21\17\1\246\5\17\16\0\1\17\3\0\13\17"+
    "\3\0\4\17\1\144\22\17\16\0\1\17\3\0\13\17"+
    "\3\0\21\17\1\225\5\17\16\0\1\17\3\0\13\17"+
    "\3\0\3\17\1\144\23\17\16\0\1\17\3\0\13\17"+
    "\3\0\4\17\1\247\22\17\16\0\1\17\3\0\13\17"+
    "\3\0\12\17\1\144\14\17\16\0\1\17\3\0\13\17"+
    "\3\0\4\17\1\34\22\17\16\0\1\17\3\0\13\17"+
    "\3\0\3\17\1\124\23\17\2\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[7865];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\1\1\3\11\3\1\1\11"+
    "\10\1\2\11\20\1\2\11\1\0\1\11\1\0\1\1"+
    "\1\0\1\11\171\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[167];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexerCUP(java.io.Reader in) {
      yyline = 1; 
    yychar = 1; 
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.out.println("Este es un error lexico: "+yytext()+
    ", en la linea: "+yyline+", en la columna: "+yychar);
            }
          // fall through
          case 25: break;
          case 2:
            { /*Ignore*/
            }
          // fall through
          case 26: break;
          case 3:
            { yychar=1;
            }
          // fall through
          case 27: break;
          case 4:
            { return new Symbol(sym.Parentesis_Izq, (int)yychar, yyline, yytext());
            }
          // fall through
          case 28: break;
          case 5:
            { return new Symbol(sym.Parentesis_Der, (int)yychar, yyline, yytext());
            }
          // fall through
          case 29: break;
          case 6:
            { return new Symbol(sym.Coma,(int) yychar, yyline, yytext());
            }
          // fall through
          case 30: break;
          case 7:
            { return new Symbol(sym.Numero,(int) yychar, yyline, yytext());
            }
          // fall through
          case 31: break;
          case 8:
            { return new Symbol(sym.PuntoComa,(int) yychar, yyline, yytext());
            }
          // fall through
          case 32: break;
          case 9:
            { return new Symbol(sym.Operador_comparativo, (int)yychar, yyline, yytext());
            }
          // fall through
          case 33: break;
          case 10:
            { return new Symbol(sym.Asigna,(int) yychar, yyline, yytext());
            }
          // fall through
          case 34: break;
          case 11:
            { return new Symbol(sym.Identificador, (int)yychar, yyline, yytext());
            }
          // fall through
          case 35: break;
          case 12:
            { return new Symbol(sym.Corchete_Izq,(int) yychar, yyline, yytext());
            }
          // fall through
          case 36: break;
          case 13:
            { return new Symbol(sym.Corchete_Der, (int)yychar, yyline, yytext());
            }
          // fall through
          case 37: break;
          case 14:
            { return new Symbol(sym.Llave_Izq,(int) yychar, yyline, yytext());
            }
          // fall through
          case 38: break;
          case 15:
            { return new Symbol(sym.Llave_Der, (int)yychar, yyline, yytext());
            }
          // fall through
          case 39: break;
          case 16:
            { return new Symbol(sym.Literal, yyline, yycolumn, yytext().substring(1, yytext().length()-1));
            }
          // fall through
          case 40: break;
          case 17:
            { return new Symbol(sym.Bucles,(int) yychar, yyline, yytext());
            }
          // fall through
          case 41: break;
          case 18:
            { return new Symbol(sym.Tipo_de_dato,(int) yychar, yyline, yytext());
            }
          // fall through
          case 42: break;
          case 19:
            { return new Symbol(sym.Modificador_de_acceso, (int)yychar, yyline, yytext());
            }
          // fall through
          case 43: break;
          case 20:
            { return new Symbol(sym.Principal, (int)yychar, yyline, yytext());
            }
          // fall through
          case 44: break;
          case 21:
            { return new Symbol(sym.Crear_clase, (int)yychar, yyline, yytext());
            }
          // fall through
          case 45: break;
          case 22:
            { return new Symbol(sym.Imprime, (int)yychar, yyline, yytext());
            }
          // fall through
          case 46: break;
          case 23:
            { return new Symbol(sym.Declarador_de_metodos, (int)yychar, yyline, yytext());
            }
          // fall through
          case 47: break;
          case 24:
            { return new Symbol(sym.Devuelve_valor, (int) yychar, yyline, yytext());
            }
          // fall through
          case 48: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
