
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadorlexicozamoranoomar;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Parentesis_Der = 6;
  public static final int Corchete_Der = 19;
  public static final int Abridor_de_archivos = 36;
  public static final int Incremento = 30;
  public static final int Declarador_de_metodos = 18;
  public static final int PuntoComa = 7;
  public static final int Coma = 3;
  public static final int Constructor = 33;
  public static final int Literal = 9;
  public static final int Operador_comparativo = 23;
  public static final int Devuelve_valor = 13;
  public static final int Decremento = 31;
  public static final int Tipo_de_dato = 12;
  public static final int Crear_clase = 21;
  public static final int Error = 10;
  public static final int Principal = 17;
  public static final int Llave_Der = 15;
  public static final int Ingresa = 35;
  public static final int Asigna = 14;
  public static final int Ciclo_Para = 29;
  public static final int Ciclo_Mientras = 22;
  public static final int Punto = 32;
  public static final int Generador_de_objetos = 34;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Parentesis_Izq = 5;
  public static final int Corchete_Izq = 20;
  public static final int Modificador_de_acceso = 11;
  public static final int Sino_pregunta = 28;
  public static final int Imprime = 4;
  public static final int Agregador = 25;
  public static final int Identificador = 2;
  public static final int Si = 26;
  public static final int Sino = 27;
  public static final int Llave_Izq = 16;
  public static final int Importar = 24;
  public static final int Numero = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Identificador",
  "Coma",
  "Imprime",
  "Parentesis_Izq",
  "Parentesis_Der",
  "PuntoComa",
  "Numero",
  "Literal",
  "Error",
  "Modificador_de_acceso",
  "Tipo_de_dato",
  "Devuelve_valor",
  "Asigna",
  "Llave_Der",
  "Llave_Izq",
  "Principal",
  "Declarador_de_metodos",
  "Corchete_Der",
  "Corchete_Izq",
  "Crear_clase",
  "Ciclo_Mientras",
  "Operador_comparativo",
  "Importar",
  "Agregador",
  "Si",
  "Sino",
  "Sino_pregunta",
  "Ciclo_Para",
  "Incremento",
  "Decremento",
  "Punto",
  "Constructor",
  "Generador_de_objetos",
  "Ingresa",
  "Abridor_de_archivos"
  };
}

