
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadorlexicozamoranoomar;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Bucles = 22;
  public static final int Declarador_de_metodos = 18;
  public static final int Numero = 8;
  public static final int Parentesis_Izq = 5;
  public static final int Operador_comparativo = 23;
  public static final int Parentesis_Der = 6;
  public static final int Asigna = 14;
  public static final int Identificador = 2;
  public static final int Corchete_Izq = 20;
  public static final int Corchete_Der = 19;
  public static final int Coma = 3;
  public static final int Crear_clase = 21;
  public static final int Tipo_de_dato = 12;
  public static final int EOF = 0;
  public static final int Llave_Izq = 16;
  public static final int error = 1;
  public static final int Devuelve_valor = 13;
  public static final int Llave_Der = 15;
  public static final int Imprime = 4;
  public static final int Literal = 9;
  public static final int Modificador_de_acceso = 11;
  public static final int PuntoComa = 7;
  public static final int Error = 10;
  public static final int Principal = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Identificador",
  "Coma",
  "Imprime",
  "Parentesis_Izq",
  "Parentesis_Der",
  "PuntoComa",
  "Numero",
  "Literal",
  "Error",
  "Modificador_de_acceso",
  "Tipo_de_dato",
  "Devuelve_valor",
  "Asigna",
  "Llave_Der",
  "Llave_Izq",
  "Principal",
  "Declarador_de_metodos",
  "Corchete_Der",
  "Corchete_Izq",
  "Crear_clase",
  "Bucles",
  "Operador_comparativo"
  };
}

